services:
    cv_user.registration.form.type:
        class: CV\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: cv_user_registration }