<?php

namespace CV\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository {

   	public function requestCarUser($idProfile) {
		
    $query = $this->createQueryBuilder('c')
      ->leftJoin('c.profile', 'profile')
      ->addSelect('profile')
      ->where('c.profile = :profile')
      ->setParameter('profile', $idProfile)
      ->getQuery();

    return $query->getResult();
   	}

}
