<?php

namespace CV\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PreferenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreferenceRepository extends EntityRepository
{

   	public function requestPreferenceUser($idProfile) {

	    $query = $this->createQueryBuilder('p')
      ->leftJoin('p.profile', 'profile')
      ->addSelect('profile')
      ->where('p.profile = :profile')
      ->setParameter('profile', $idProfile)
      ->getQuery();

      return $query->getSingleResult();
  }
}
