<?php

namespace CV\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{
   	public function requestProfileUser($userId) {
		
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.user', 'user')
            ->addSelect('user')
            ->where('p.user = :user')
            ->setParameter('user', $userId)
            ->getQuery();

        return $query->getSingleResult();
   	}

    public function requestProfileUsers() {
    
        $query = $this->createQueryBuilder('p')
            ->leftJoin('p.user', 'user')
            ->addSelect('user')
            ->getQuery();

        return $query->getResult();
    }
}
