<?php

namespace CV\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends EntityRepository
{

   	public function requestProfileUser($idUser) {
		
    $query = $this->createQueryBuilder('p')
      ->leftJoin('p.user', 'user')
      ->addSelect('user')
      ->where('p.user = :user')
      ->setParameter('user', $idUser)
      ->getQuery();

    return $query->getSingleResult();
   	}
}
