cv_platform_home:
    path:      /
    defaults:  { _controller: CVPlatformBundle:Platform:index }
    requirements:
        page: \d*

cv_platform_view:
    path:      /ride/{id}
    defaults:  { _controller: CVPlatformBundle:Ride:view }
    requirements:
        id: \d+

cv_platform_add:
    path:      /offer-seats
    defaults:  { _controller: CVPlatformBundle:Ride:add }

cv_platform_edit:
    path:      /trip/edit/{id}
    defaults:  { _controller: CVPlatformBundle:Ride:edit }
    requirements:
        id: \d+

cv_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: CVPlatformBundle:Ride:delete }
    requirements:
        id: \d+

cv_platform_upcoming_rides:
    path:      /trip-offers/active/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:upcomingRides, page: 1 }
    requirements:
        page: \d*

cv_platform_past_rides:
    path:      /trip-offers/inactive/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:pastRides, page: 1 }
    requirements:
        page: \d*

cv_platform_my_rides:
    path:      /my-rides/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:myRides, page: 1 }
    requirements:
        page: \d*

cv_platform_search_rides:
    path:      /search-car-sharing
    defaults:  { _controller: CVPlatformBundle:Ride:searchRidesUser }

cv_platform_focus_rides:
    path:      /focus-rides/{departure}/{arrival}/{departureDate}/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:focusRidesUser, page: 1 }
    requirements:
        page: \d*

cv_platform_reservation:
    path:      /manage-my-booking/{id}
    defaults:  { _controller: CVPlatformBundle:Reservation:view }
    requirements:
        id: \d+

cv_platform_add_private_message:
    path:      /add-private-message/{id}
    defaults:  { _controller: CVPlatformBundle:PrivateMessage:add }

cv_platform_add_public_message:
    path:      /reservation-ride/add_public_message/{ride}
    defaults:  { _controller: CVPlatformBundle:PublicMessage:add }

cv_platform_confirm_reservation_ride:
    path:      /confirm-reservation-ride/{id}
    defaults:  { _controller: CVPlatformBundle:Reservation:confirm }
    requirements:
        id: \d+

cv_platform_current_reservations:
    path:      /my-bookings/{page}
    defaults:  { _controller: CVPlatformBundle:Reservation:currentReservations, page: 1 }
    requirements:
        page: \d*

cv_platform_past_reservations:
    path:      /my-bookings/history/{page}
    defaults:  { _controller: CVPlatformBundle:Reservation:pastReservations, page: 1 }
    requirements:
        page: \d*

cv_platform_private_messages_received:
    path:      /private-messages-received/{page}
    defaults:  { _controller: CVPlatformBundle:PrivateMessage:messagesReceived, page: 1 }
    requirements:
        page: \d*

cv_platform_private_messages_sended:
    path:      /private-messages-sended/{page}
    defaults:  { _controller: CVPlatformBundle:PrivateMessage:messagesSended, page: 1 }
    requirements:
        page: \d*


cv_platform_public_messages_received:
    path:      /public-messages-received/{page}
    defaults:  { _controller: CVPlatformBundle:PublicMessage:messagesReceived, page: 1 }
    requirements:
        page: \d*

cv_platform_public_messages_sended:
    path:      /public-messages-sended/{page}
    defaults:  { _controller: CVPlatformBundle:PublicMessage:messagesSended, page: 1 }
    requirements:
        page: \d*

cv_platform_my_notifications:
    path:      /my-notifications/{page}
    defaults:  { _controller: CVPlatformBundle:Notification:myNotifications, page: 1 }
    requirements:
        page: \d*

cv_platform_ratings_received:
    path:      /ratings-received/
    defaults:  { _controller: CVPlatformBundle:Rating:received }

cv_platform_ratings_sended:
    path:      /ratings-sended/{page}
    defaults:  { _controller: CVPlatformBundle:Rating:sended, page: 1 }
    requirements:
        page: \d*

cv_platform_leave_rating:
    path:      /leave-rating/{id}
    defaults:  { _controller: CVPlatformBundle:Rating:leave }
    requirements:
        id: \d+

cv_platform_delete_rating_notification:
    path:      /delete-rating-notification
    defaults:  { _controller: CVPlatformBundle:Notification:deleteRatingNotification }

cv_platform_validate_payment:
    path:      /validate-payment
    defaults:  { _controller: CVPlatformBundle:Payment:validate }

cv_platform_dashboard:
    path:      /dashboard
    defaults:  { _controller: CVPlatformBundle:Dashboard:view }