cv_platform_home:
    path:      /
    defaults:  { _controller: CVPlatformBundle:Platform:index }
    requirements:
        page: \d*

cv_platform_view:
    path:      /ride/{id}
    defaults:  { _controller: CVPlatformBundle:Ride:view }
    requirements:
        id: \d+

cv_platform_add:
    path:      /add
    defaults:  { _controller: CVPlatformBundle:Ride:add }

cv_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: CVPlatformBundle:Ride:edit }
    requirements:
        id: \d+

cv_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: CVPlatformBundle:Ride:delete }
    requirements:
        id: \d+

cv_platform_upcoming_rides:
    path:      /upcoming-rides/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:upcomingRides, page: 1 }
    requirements:
        page: \d*

cv_platform_past_rides:
    path:      /past-rides/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:pastRides, page: 1 }
    requirements:
        page: \d*

cv_platform_my_rides:
    path:      /my-rides/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:myRides, page: 1 }
    requirements:
        page: \d*

cv_platform_search_rides:
    path:      /search-rides
    defaults:  { _controller: CVPlatformBundle:Ride:searchRidesUser }

cv_platform_focus_rides:
    path:      /focus-rides/{departure}/{arrival}/{departure_date}/{page}
    defaults:  { _controller: CVPlatformBundle:Ride:focusRidesUser, page: 1 }
    requirements:
        page: \d*

cv_platform_reservation_ride:
    path:      /reservation-ride/{id}
    defaults:  { _controller: CVPlatformBundle:Reservation:add }
    requirements:
        id: \d+

cv_platform_add_public_message:
    path:      /reservation-ride/add_public_message/{ride}
    defaults:  { _controller: CVPlatformBundle:PublicMessage:add }

cv_platform_confirm_reservation_ride:
    path:      /confirm-reservation-ride/{id}
    defaults:  { _controller: CVPlatformBundle:Reservation:confirm }
    requirements:
        id: \d+

cv_platform_current_reservations:
    path:      /current-reservations/{page}
    defaults:  { _controller: CVPlatformBundle:Reservation:currentReservations, page: 1 }
    requirements:
        page: \d*

cv_platform_past_reservations:
    path:      /past-reservations/{page}
    defaults:  { _controller: CVPlatformBundle:Reservation:pastReservations, page: 1 }
    requirements:
        page: \d*

cv_platform_my_reservations:
    path:      /my-reservations/{page}
    defaults:  { _controller: CVPlatformBundle:Reservation:myReservations, page: 1 }
    requirements:
        page: \d*

cv_platform_messages_received:
    path:      /messages-received/{page}
    defaults:  { _controller: CVPlatformBundle:PublicMessage:messagesReceived, page: 1 }
    requirements:
        page: \d*

cv_platform_messages_sended:
    path:      /messages-sended/{page}
    defaults:  { _controller: CVPlatformBundle:PublicMessage:messagesSended, page: 1 }
    requirements:
        page: \d*

cv_platform_ratings:
    path:      /ratings/{page}
    defaults:  { _controller: CVPlatformBundle:Rating:leave, page: 1 }
    requirements:
        page: \d*

cv_platform_delete_rating_notification:
    path:      /delete-rating-notification
    defaults:  { _controller: CVPlatformBundle:Rating:deleteNotification }