<?php

namespace CV\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
	public function update($userId) {
		$query = $this->_em->createQuery('
				SELECT r, ride FROM CVPlatformBundle:Reservation r
		        JOIN r.ride ride
				WHERE r.user = :user
				AND r.state = 0
				AND ride.departureDate < :now
		        AND NOT EXISTS (
		        	SELECT ra
		        	FROM CVPlatformBundle:Rating ra
		        	WHERE ra.user = :user
		        	AND ra.relateduser = ride.user
		        )
				GROUP BY ride.user')
			->setParameter('user', $userId)
			->setParameter('now', date('Y-m-d H:i:s'));

		foreach ($query->getResult() as $reservation) {
          	$notification = new Notification($reservation->getUser(), $reservation->getRide()->getUser());
            $this->_em->persist($notification);
            $this->_em->flush();
        }
	}

	public function numberOfUser($userId) {
        $query = $this->_em->createQuery('
                SELECT COUNT(n.id) 
                FROM CVPlatformBundle:Notification n
                WHERE n.user = :user')
        	->setParameter('user', $userId);
        return $query->getSingleScalarResult();
   	}
}
