<?php

namespace CV\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PrivateMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateMessageRepository extends EntityRepository
{

	public function messagesSended($page, $nbPerPage, $userId) {
		$query = $this->_em->createQuery('
			SELECT p FROM CVPlatformBundle:PrivateMessage p
			WHERE p.user = :user
			ORDER BY p.date DESC')
		->setParameter('user', $userId);

		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}

	public function messagesReceived($page, $nbPerPage, $userId) {
		$query = $this->_em->createQuery('
			SELECT p FROM CVPlatformBundle:PrivateMessage p
			WHERE p.relatedUser = :user
			ORDER BY p.date DESC')
		->setParameter('user', $userId);

		$query
		->setFirstResult(($page-1) * $nbPerPage)
		->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}  
}
