<?php

namespace CV\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicMessageRepository extends EntityRepository
{
    public function publicMessagesOfRide($ride) {
      	$listpublicMessagesOfRide = $this->findBy(
  			array('ride' => $ride), 
  			array('date' => 'ASC'),        
  			null,                              
  			0                   
		);

      	return $listpublicMessagesOfRide;
    }
}
