<?php

namespace CV\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
	public function updateStates($userId) {
	  	$query = $this->createQueryBuilder('r')
	      	->join('r.ride', 'ride')
	      	->addSelect('ride')
	      	->where('r.user = :user')
	      		->setParameter('user', $userId)
	      	->getQuery();

	  	$now = date('Y-m-d H:i:s');

        foreach ($query->getResult() as $reservation) {
            if ( $reservation->getRide()->getDepartureDate() < $now && $reservation->getState() == 0 ) {
                $reservation->setState(1);
            }
        }

        $this->_em->flush();
	}

   	public function numberNotify($userId){
        $query = $this->_em->createQuery('
                SELECT COUNT(re.id) FROM CVPlatformBundle:Reservation re
                JOIN re.ride ri
                WHERE re.ride = ri
                AND re.state = 1
                AND re.user = :user')
        	->setParameter('user', $userId);

        return $query->getSingleScalarResult();
   	}

	public function currentReservations($page, $nbPerPage, $userId) {	
	  	$query = $this->createQueryBuilder('r')
	      	->join('r.ride', 'ride')
	      	->addSelect('ride')
	      	->where('r.user = :user')
	      		->setParameter('user', $userId)
	      	->andWhere('r.state = 0')
	      	->getQuery();

        $query
          	->setFirstResult(($page-1) * $nbPerPage)
          	->setMaxResults($nbPerPage);

	    return new Paginator($query, true);
   	}

   	public function pastReservations($page, $nbPerPage, $userId) {	
	  	$query = $this->createQueryBuilder('r')
	      	->join('r.ride', 'ride')
	      	->addSelect('ride')
	      	->where('r.user = :user')
	      		->setParameter('user', $userId)
	      	->andWhere('r.state = 1')
	      	->getQuery();

        $query
          	->setFirstResult(($page-1) * $nbPerPage)
          	->setMaxResults($nbPerPage);

	    return new Paginator($query, true);
	}

	public function myReservations($page, $nbPerPage, $userId) {	
	    $query = $this->createQueryBuilder('r')
	      	->join('r.ride', 'ride')
	      	->addSelect('ride')
	      	->where('r.user = :user')
	      		->setParameter('user', $userId)
	      	->orderBy('ride.offerPublished', 'DESC')
	      	->getQuery();

        $query
          	->setFirstResult(($page-1) * $nbPerPage)
          	->setMaxResults($nbPerPage);
	    return new Paginator($query, true);
   	}
}
